### ISSUE TITLE
Can be placed in worldguard area

### ISSUE THREAD

**Issue by cRestalious** [Ste3et/FurnitureLib#100]
So I tried placing a furniture on an area that was protected and it worked... Is there any way to prevent that?
![image](https://github.com/Ste3et/FurnitureLib/assets/115401374/37b93b3c-6345-4b80-855c-b779c5fb128c)

**Comment by Ste3et** [comment]
Install the ProtectionLib on your server 

https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/
https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.12.x%20-%201.20.x&commit=3b82bf26
