### ISSUE TITLE
Furniture chunk limit not work.

### ISSUE THREAD

**Issue by andris155** [Ste3et/FurnitureLib#14]
Server restart - reset limit.
Change gamemode - reset limit.

**Comment by Ste3et** [comment]
what deos you mean ?

**Comment by andris155** [comment]
Möbelstück funktioniert nicht

server neustart - Rücksetzgrenze
gamemode ändern - Rücksetzgrenze

Gamemode survival -> Platzierung Möbel 1/10 , und einmal mehr, so 2/10 -> /gamemode creative -> Platzierung Möbel 1/10 .. So dass es zurückgesetzt wird
