### ISSUE TITLE
Improved Player Limit Feature

### ISSUE THREAD

**Issue by BiGUNMAN** [Ste3et/FurnitureLib#17]
The limits are awesome, and I really appreciate them, but they are a bit limited.

It would be super useful if we could set a limit on the total amount of furniture a player can place. So instead of just limiting how much of 1 specific furniture, you can say the maximum this player can place is X amount of furniture.

It would just be an additional limit, like furniture.limit.total.rank1
Or, it could be an additional line to the permissionsLimit: section. So it would look like this instead:
http://pastebin.com/qwdB1vm8

**Comment by BiGUNMAN** [comment]
@Ste3et So was this just dismissed or would it be added?

**Comment by Ste3et** [comment]
Iam finish with it but i cannot release the update at the moment.

**Comment by BiGUNMAN** [comment]
Alright, thanks! I also would like to suggest a "total per chunk" limit. It would be really useful too.
