### ISSUE TITLE
Copying items

### ISSUE THREAD

**Issue by Dorii2003** [Ste3et/FurnitureLib#19]
You can copy objects, just have 2 for example wood and click:
Right mouse button (do not drop your finger from the button), once Q and then start copying.

**Comment by Ste3et** [comment]
Doesn't know what you mean sorry.

**Comment by Dorii2003** [comment]
Oh, sorry, I forgot to add that you have to have a table, for example.
The crosshair must be on the furniture and then click those buttons that I replaced earlier (PPM + Q + PPM all the time)

**Comment by Ste3et** [comment]
I cannot reproduce it sorry i have test it so:

place a diamond on the table (hold right mouse button) and drop it but this have no effects then you are in gamemode 1 this is normal.

**Comment by Dorii2003** [comment]
Sorry, I missed the plugin update, after the update is good. Sorry, and thank you
