### ISSUE TITLE
FurnitureLib 

### ISSUE THREAD

**Issue by Blamo27** [Ste3et/FurnitureLib#2]
http://timings.aikar.co/?url=15230414
FurnitureLib is causing a bug, while I remove It, bugs disapear.
=> ProtocolLib version: 3.6.5
=> Vault version: 1.5.6-b49
=> Spigot version: 1.8.8-R0.1

**Comment by Blamo27** [comment]
@Ste3et ?

**Comment by Ste3et** [comment]
1.8.8 have no support.
