### ISSUE TITLE
hidden furniture on torchspigot and paperspigot

### ISSUE THREAD

**Issue by mat41997** [Ste3et/FurnitureLib#22]
ss
![2017-04-29_16 51 58](https://cloud.githubusercontent.com/assets/5884000/25556403/5017f70c-2cfc-11e7-9bcb-956a0b341dbf.png)
![2017-04-29_16 52 07](https://cloud.githubusercontent.com/assets/5884000/25556406/61586042-2cfc-11e7-8da7-a7ee57fba4bd.png)
![2017-04-29_16 52 13](https://cloud.githubusercontent.com/assets/5884000/25556409/65e14052-2cfc-11e7-8f8a-8e14f88bbcd7.png)
![2017-04-29_16 52 22](https://cloud.githubusercontent.com/assets/5884000/25556410/69adfba8-2cfc-11e7-808c-4478e1fdca57.png)

torchspigot
https://github.com/TorchSpigot/Torch
https://circleci.com/gh/TorchSpigot/Torch/97#artifacts/containers/0

timings
https://timings.aikar.co/?id=f5928f9c696c4afdba4a3ededfbd09a9

**Comment by Ste3et** [comment]
I have test it to reproduce your probleme i have test it with the latest paperspigot/torchspigot but for me it deos not hide the furniture. can you give me your latest.log to check it for problems with another packet plugins ?

**Comment by Ste3et** [comment]
have you change something on the render distance ?

**Comment by mat41997** [comment]
see timings
![2017-04-30 12_51_52-aikar s timings viewer](https://cloud.githubusercontent.com/assets/5884000/25563804/0a8f35e4-2da4-11e7-8421-06a45cb17712.png)

**Comment by mat41997** [comment]
i no have the log

**Comment by mat41997** [comment]
On my other server this bug does not occur : O

**Comment by mat41997** [comment]
you must left of the chunk, to reproduce this bug

**Comment by Ste3et** [comment]
oha you set the view distance of your server of 3 this is very low 🤔

**Comment by mat41997** [comment]
it is not a problem
3 is very good distance

**Comment by Ste3et** [comment]
ok it is not the problem i know it, but i think this is very funny ^^, this is how do you can fix it:

your chunkview is 3 chunks and the furniture have a default view distance from 100 blocks, 3 chunks are 48 blocks, look in the config.yml and set the viewDistance to 48 and test the problem again.

**Comment by Ste3et** [comment]
optional you can test this developer build: https://www.dropbox.com/s/d2kdmhdihqnjq9n/FurnitureLib.zip?dl=0

**Comment by mat41997** [comment]
![2017-04-30_13 43 44](https://cloud.githubusercontent.com/assets/5884000/25564089/1183e5aa-2dab-11e7-9e9b-bcbbc17364b2.png)

**Comment by Ste3et** [comment]
ok now i have remove the debug messages of the developer build https://www.dropbox.com/s/d2kdmhdihqnjq9n/FurnitureLib.zip?dl=0

**Comment by mat41997** [comment]
thx.

**Comment by Ste3et** [comment]
thx for the bug report a solid build comes today, but before i can release i must be fixe some little bugs.

**Comment by mat41997** [comment]
oh no!

![2017-05-01_11 49 25](https://cloud.githubusercontent.com/assets/5884000/25577127/48a34f94-2e64-11e7-854a-eaaeb38317d7.png)

timings
https://timings.aikar.co/?id=545101d60bd54bf4adba275071cca3b6

to reproduct
use command /speed 10

**Comment by Ste3et** [comment]
and why you want this i cannot do it faster.

**Comment by Ste3et** [comment]
i have test it for me it deos work with the fly speed.

**Comment by Ste3et** [comment]
i have it test on your server it does work in 5/10 try
