### ISSUE TITLE
ProtocolSupport on 1.12 pre 5 messes up Furniture

### ISSUE THREAD

**Issue by Fonzee9** [Ste3et/FurnitureLib#25]
Link to ProtocolSupport for 1.12 pre 5: https://mega.nz/#!IwFCULyQ!0RqOeI-JEIjUeX0TS07M_ZvNVbo7hWZNy_WRqRFUlCA

![2017-05-24_11 01 19](https://cloud.githubusercontent.com/assets/21323258/26410163/7744538e-4070-11e7-997f-cae8246e647b.png)

**Comment by Fonzee9** [comment]
This is how it looks on 1.12 pre 5 after putting ProtocolSupport in

**Comment by Ste3et** [comment]
it is not my protblem i think.

**Comment by Fonzee9** [comment]
It is this problem also happens with ViaVersion please fix this problem :) So many servers use ProtocolSupport and ViaVersion if you don't fix this so many people will just stop using this wonderful plugin.

**Comment by Ste3et** [comment]
i cannot test it my client crash then i connect to the ProtocolSupport 1.12 Spigot,
it is not my problem i cannot support every plugin of this planet.

**Comment by Fonzee9** [comment]
This is someone who installed FurnitureLib on there server that uses ViaVersion: Incredible plugin! Works flawlessly. Would it be possible to add support for FurnitureLib and DiceFurniture so in 1.9, 1.10, and 1.11 on a 1.8 server, furniture doesn't get all messed up?

**Comment by Fonzee9** [comment]
https://github.com/MylesIsCool/ViaVersion/issues/335

**Comment by Ste3et** [comment]
no 1.8 support. Mojang change to mutch in the 1.9 i cannot support 1.8.

https://bugs.mojang.com/secure/attachment/95133/C.png

**Comment by Ste3et** [comment]
http://imgur.com/a/r5nPF

**Comment by Fonzee9** [comment]
No i wanted 1.9 - 1.12 support for FurnitureLib don't care about 1.8

**Comment by Ste3et** [comment]
At the moment it gives no protocolSupport for 1.12-pre5

**Comment by Fonzee9** [comment]
This is ProtocolSupport for 1.12 pre 5:

https://mega.nz/#!IwFCULyQ!0RqOeI-JEIjUeX0TS07M_ZvNVbo7hWZNy_WRqRFUlCA

**Comment by Ste3et** [comment]
This version deos not work on 1.12 pre 5 clients wait for a stable release.
Clients cannot send messages and place items.

**Comment by Fonzee9** [comment]
Okay then use 1.11.2 same problem happens 
https://www.spigotmc.org/resources/protocolsupport.7201/

**Comment by Ste3et** [comment]
doesnt know what is the problem for me it deos work: 

- http://i.imgur.com/lVXSppq.png
- http://i.imgur.com/HuxuUET.png

can you send me your complete latest.log ?

**Comment by Fonzee9** [comment]
Hmm i'll try a 1.12 build that is more stable then.
