### ISSUE TITLE
FurnitureLib glitch with Billboard lets players get Barrier Blocks

### ISSUE THREAD

**Issue by Fonzee9** [Ste3et/FurnitureLib#26]
![2017-06-01_10 54 20](https://cloud.githubusercontent.com/assets/21323258/26685770/04d283ee-46b9-11e7-833c-6cc0993bb85a.png)

**Comment by Fonzee9** [comment]
Basically if you destroy the billboard those 6 barriers don't get destroyed with it and stay

**Comment by Fonzee9** [comment]
Also you can get infinite beds with a tent

**Comment by Ste3et** [comment]
The billboard is never full implement, it is not for Players The another bug i Look at it.
