### ISSUE TITLE
High tick usage %

### ISSUE THREAD

**Issue by BBoyJD10** [Ste3et/FurnitureLib#32]
FurnitureLib v1.9.4-DEV_5

0.29%	1,183.23%	  4.14 s	   591.61 ms	 0.0	       0.0k	    Task: ChunkOnLoad$6(Single)

**Comment by Ste3et** [comment]
Please test this development build: http://cardinal.dicecraft.de:8080/job/FurnitureLib/19/ and send me the complete Timings

**Comment by BBoyJD10** [comment]
08.01 06:23:59 [Server] WARN java.lang.IllegalStateException: Asynchronous entity add!
08.01 06:23:59 [Server] WARN at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
08.01 06:23:59 [Server] WARN at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1116)
08.01 06:23:59 [Server] WARN at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1138)
08.01 06:23:59 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.addEntity(CraftWorld.java:1266)
08.01 06:23:59 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawn(CraftWorld.java:1273)
08.01 06:23:59 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawn(CraftWorld.java:908)
08.01 06:23:59 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnEntity(CraftWorld.java:408)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.main.FurnitureManager.createNew(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.main.FurnitureManager.getDefaultWatcher(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.main.entity.fProtocol.<init>(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.main.entity.fSerializer.<init>(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.main.entity.fEntity.<init>(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.main.entity.fArmorStand.<init>(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.main.FurnitureManager.createArmorStand(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.Database.DeSerializer.loadArmorStandMetadata(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.Database.DeSerializer.Deserialze(Unknown Source)
08.01 06:23:59 [Server] WARN at de.Ste3et_C0st.FurnitureLib.Database.Database$2.run(Unknown Source)
08.01 06:23:59 [Server] WARN at java.lang.Thread.run(Thread.java:745)
08.01 06:24:00 [Connect] User LokiPoki305, IP 93.137.230.111
08.01 06:24:00 [Server] WARN java.lang.IllegalStateException: Asynchronous entity add!
08.01 06:24:00 [Server] WARN at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
08.01 06:24:00 [Server] WARN at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1116)
08.01 06:24:00 [Server] WARN at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1138)
08.01 06:24:00 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.addEntity(CraftWorld.java:1266)
08.01 06:24:00 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawn(CraftWorld.java:1273)
08.01 06:24:00 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawn(CraftWorld.java:908)
08.01 06:24:00 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.spawnEntity(CraftWorld.java:408)
08.01 06:24:00 [Server] WARN at de.Ste3et_C0st.FurnitureLib.main.FurnitureManager.createNew(Unknown Source)

new error occured

**Comment by Ste3et** [comment]
Ok sorry this was a wrong change in a previous build i mean i have fix it: http://136.243.170.173:8080/job/FurnitureLib/21/
