### ISSUE TITLE
Crashes server

### ISSUE THREAD

**Issue by BBoyJD10** [Ste3et/FurnitureLib#35]
Crashes server while trying to load in the furniture

Error log:

https://pastebin.com/9W1694i4

**Comment by Ste3et** [comment]
Did this test work for you http://136.243.170.173:8080/job/FurnitureLib/27/ it is my last test before i start the reworke.

**Comment by BBoyJD10** [comment]
Same issue still happens with that version

**Comment by Ste3et** [comment]
Damn async shit i recode it completely back idk Why for me it deos Work and for Otter People Not. #FuckYouAsync😠 i Need a Week to code it back.

**Comment by BBoyJD10** [comment]
When we get the fixed version ?

**Comment by Ste3et** [comment]
it must be fixed
