### ISSUE TITLE
PlotSquared Compatibility

### ISSUE THREAD

**Issue by Drc-DEV** [Ste3et/FurnitureLib#42]
The plugin does not block players placing furniture outside their plots in 1.13.2 with latest plotsquared https://ci.athion.net/job/PlotSquared/646/

You could easily make this plugin compatibile with anything by throwing a fake blockplace event and checking if it was cancelled or not.......

**Comment by Ste3et** [comment]
This is not a option to work around it the LogBlock plugin or CoreProtect make problems with custom blockplace events the next reason with it is the check if the player is an owner of the region and can destroy everything. With the blockplace event i cannot remove every furniture on region clearing.

**Comment by Drc-DEV** [comment]
I can't understand what you are saying.

Anyways this is still a bug, rendering FurnitureLib unable to be used at all with PlotSquared.
