### ISSUE TITLE
"10" spam in console

### ISSUE THREAD

**Issue by OpalMoonstride** [Ste3et/FurnitureLib#45]
I'm not sure if it's an error, or if it's just leftover debug spam. Can I turn it off?

I just get [INFO]: 10 
https://pastebin.com/FsxQE2qF

Paper Spigot 1.13.2-R0.1-SNAPSHOT
ProtectionLib 106
FurnitureLib 109
FurnitureMaker 108

**Comment by Ste3et** [comment]
https://build.dicecraft.de/furniturelib/furniturelib-1.13/commit/8ac1941a2e27fb96fa52029bf16ec3bbfda2a6e5#e5911ac15d9d3717ea992da569cb4bd1a298b308 is your furniturelib not furniturelib build #108 ?

**Comment by OpalMoonstride** [comment]
Well, I don't know. I downloaded it yesterday, before opening an issue, and it still spammed 10. Downloaded today, after your answer, and it was fine. I label my jars with numbers so not sure why it would be 108. 

Anyway, it's gone. lol.
