### ISSUE TITLE
Plants disappearing from pots

### ISSUE THREAD

**Issue by OpalMoonstride** [Ste3et/FurnitureLib#46]
Paper Spigot 1.13.2-R0.1-SNAPSHOT
ProtectionLib 106
FurnitureLib 109
FurnitureMaker 108

Plants disappear from pots on sever restart.

**Comment by Ste3et** [comment]
https://dicecraft.de/furniture/download.php?plugin=DiceFurniture&build=DevBuild&version=Spigot%201.13.x&buildNummer=105

**Comment by OpalMoonstride** [comment]
Oh, thought I had the recent one. Thanks!
