### ISSUE TITLE
Need recode LightManager

### ISSUE THREAD

**Issue by BeYkeRYkt** [Ste3et/FurnitureLib#5]
In studying your [code](https://github.com/Ste3et/FurnitureLib/blob/master/src/de/Ste3et_C0st/FurnitureLib/main/LightManager.java), I have noticed that you are calling incorrectly update chunks.
Your code only updates the one piece of the chunk. Since light can affect other chunks, I would recommend to call the update as [here](https://gist.github.com/BeYkeRYkt/470ff32cde7003e06a2277a0ce3735ce). This will prevent uneven chunks updates)

**Comment by Ste3et** [comment]
thanks i have fix it.
