### ISSUE TITLE
"Key not found" for some messages

### ISSUE THREAD

**Issue by Dymeth** [Ste3et/FurnitureLib#52]
There are some messages loading incorrectly:
SideNotFound (Command\objectToSide.java)
SideNavigation (Command\objectToSide.java)
NoPermissions (main\Protection\ProtectionManager.java)

And some messages from commented part in LimitationManager.java:
LimitReachedWorld
LimitReachedChunk
LimitAouncerMaximum
LimitReachedMaximum
LimitAouncer
LimitReached

P.S. Please add key of failed message on error message "key no found": "Key NoPermissions not found", for example

**Comment by Ste3et** [comment]
Commit 7f4f5f0e865642428fa93a40e0e93dbbaad6270b add these feature
