### ISSUE TITLE
chunk limitation error

### ISSUE THREAD

**Issue by MaxIsV** [Ste3et/FurnitureLib#53]
Hello. I am having a problem with Chunk limitation. When I put "limitConfig: CHUNK" then when I try to put any furniture, an error appears in the console: https://pastebin.com/wqTmQDk0

Helpful information:
Core: Paperspigot-1.12.2
FurnitureLib-2.1.7
DiceFurniture-3.4.1

**Comment by Ste3et** [comment]
I think your problem hase been fixed -> #cf0fabe255c042cf2cf00c790d529bf1e002bf00
you can find the artifact here: https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.9.x%20-%201.15.x&buildNummer=108699822

**Comment by MaxIsV** [comment]
You know, I was probably misunderstood. Chunk restriction works fundamentally wrong. I have included "limitation / chunk ChunkLimit.total.enable: true". This should limit the total number of furniture per chunk, but it limits each model individually. If I put 3 "TV" and 3 "Bush" in one chunk, then in total there will be 6 furniture in the chunk. I want the furniture to be limited all together, which is in one chunk

**Comment by Ste3et** [comment]
Ok i have understand your request, there isn't a fast way to implement it, i need to rework the limitation thing but atm i didn't have motivation to do that i hope i can start the next weekend.

**Comment by Ste3et** [comment]
Ok @MaxIsV the problem was the config file, it is releay confuse to rework the intere sytem, every time i start the work on the code i sit for my computer and thing how can i do it in the best way, before you wait longer i add a work a round i hope it works for you, you need to add these to your limit file "ChunkLimit.total.global:true"

**Comment by Ste3et** [comment]
You can find the artifact here: https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.9.x%20-%201.15.x&buildNummer=111160620

**Comment by MaxIsV** [comment]
Thank you very much! Everything works fine, I am very glad that you solved my problem so quickly!
