### ISSUE TITLE
NPE on PlayerInteractEvent

### ISSUE THREAD

**Issue by nicuch** [Ste3et/FurnitureLib#55]
This error is getting spammed on my server:
https://gist.github.com/nicuch/5f19ac01c5ad0d0a679e2aed5228bf04
Plugin version: 2.1.8
Server version: git-Paper-72 (MC: 1.15.2)

In the error I've also seen "me.rerere.matrix". I'm also gonna report the error to matrix anti-cheat.

**Comment by nicuch** [comment]
FurnitureLib#55

**Comment by Ste3et** [comment]
There is a NPE check direct over ChunkOnLoad:154 https://github.com/Ste3et/FurnitureLib/blob/5d2f3ac631d6130aaee3c5a4172761c5cc16d631/src/de/Ste3et_C0st/FurnitureLib/Events/ChunkOnLoad.java#L154 idk why the Furniturelib Run into NPE at your Situation, but for a better Analyse about the Problem i need your ! complete latest.log ! Without i didn't want to help you, and i hope the Matrix dev can help you

**Comment by nicuch** [comment]
Please read this:
https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals
Comparing enum types using "==" is null safe. I'm gonna edit that code for myself, compile it, and report back if the error is still there (if that is the solution I'll reopen the issue).
