### ISSUE TITLE
Console Warnings

### ISSUE THREAD

**Issue by BboyZeroOne** [Ste3et/FurnitureLib#59]
Can someone take a look at these console warnings? Thanks!

https://pastebin.com/3Ke0S7xi

Thank you

**Comment by Ste3et** [comment]
Please enable debugMode in the config.yml and send me your latest.log again @BboyZeroOne

**Comment by BboyZeroOne** [comment]
[latest.log](https://github.com/Ste3et/FurnitureLib/files/4337303/latest.log)

**Comment by Ste3et** [comment]
It didn't contain something about Furniture !

**Comment by BboyZeroOne** [comment]
Let me send u an updated one later
