### ISSUE TITLE
/Furniture List permissions broken

### ISSUE THREAD

**Issue by Fonzee9** [Ste3et/FurnitureLib#60]
I've tried furniture.command.list
furniture.command.list.plugin
furniture.command.list.type
furniture.command.list.world

None work and the only way for my players to use the /furniture list is furniture.admin i tried  furniture.player but that doesn't give them permission, what am i doing wrong? I don't want to give them admin perms to use /furniture list 

basically when i type /furniture list it doesn't say what permissions they need it says nothing, and no list comes up.

**Comment by SoapyPuppyX** [comment]
what was the fix for this?
