### ISSUE TITLE
FurnitureLib plugin allows lava flow into WG regions

### ISSUE THREAD

**Issue by MaxIsV** [Ste3et/FurnitureLib#61]
On my server recently lava and water began to flow into the regions, although the WGExtender plugin should prevent this. Using the poke method on the test server, I found that when disabling DiceFurniture & FurnitureLib plugins, the problem disappears. How can i fix that?

Server: paper-1.12.2
FurnitureLib: 2.2.1
DiceFurniture: 3.4.3

**Comment by MaxIsV** [comment]
I tested, FurnitureLib-2.2.2 has the same problem.

**Comment by Ste3et** [comment]
Please test these devbuild @MaxIsV https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.9.x%20-%201.15.x&buildNummer=139592195
