### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by BboyZeroOne** [Ste3et/FurnitureLib#62]
Hello! Here's a long list of Console Errors for Furniture Lib. Please take a look!

https://pastebin.com/4G9RVGfD

https://pastebin.com/6L72ZjcK

**Comment by BboyZeroOne** [comment]
https://pastebin.com/0GYb797Q

**Comment by Ste3et** [comment]
I need more informations about your system "/furniture dump" 
I can't reproduce -> https://pastebin.com/4G9RVGfD
Did you try mySQL instand of SQLite ?

**Comment by Ste3et** [comment]
Otherwise why the plugin use h2 i never build in that method into my plugin and i didn't support it did you have change something inside the Sourcecode ?
Please run "/furntiure dump" to confirm that the bug appears with normal settings !

**Comment by BboyZeroOne** [comment]
I didn't change any storage method, its by default. Here is my config.
https://pastebin.com/VKa2ngQ7

Here is my furniture dump
https://dicecraft.de/furniture/dump.php?id=OcSD3ZE2J9YPhhUW0bNAMNEriDsFw7C6
