### ISSUE TITLE
Event to get the furnitures when the furnitures is spawned in a world at the server start ?

### ISSUE THREAD

**Issue by EnderGriefeur99** [Ste3et/FurnitureLib#65]
The plugin has an event to get the furnitures when the furnitures is spawned in a world at the server start ?
Else can you add this feature please ^^ ?

**Comment by Ste3et** [comment]
That is a big performance issue then i did that for what you want it?

**Comment by EnderGriefeur99** [comment]
i need this event to spawn an hologram on furnitures

**Comment by Ste3et** [comment]
I didin't want to fire an Bukkit event on the Startup that is useless and a big Performance issue please consider an own way how you can work with it, for the exemple you can use that -> https://github.com/Ste3et/FurnitureLib/blob/17d23841d04081e23928bfec7b8b401113847e18/src/de/Ste3et_C0st/FurnitureLib/main/FurnitureManager.java#L65
