### ISSUE TITLE
[bug report]GP Abandon claim cause Dicefurniture furniture disappear

### ISSUE THREAD

**Issue by hkkongou** [Ste3et/FurnitureLib#66]
**This issue have been reported to GriefPrevention(claim) plugin issue page and they investigated and points out is not their bug. **
__Please read the following link to view GP dev's comment:__
https://github.com/TechFortress/GriefPrevention/issues/1171
video of bug:
https://user-images.githubusercontent.com/61608872/102840695-60f0ff80-443e-11eb-8351-5369b851cb55.mp4

### What happened:
_What you saw_
when removing the a claim using /abandomclaim, dicefurniture inside claim will disappear
https://user-images.githubusercontent.com/61608872/102840695-60f0ff80-443e-11eb-8351-5369b851cb55.mp4

### What was expected:
furniture keep in the same place even the claim is removed

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. make a claim
2. put furniture inside claim
3. abandonclaim

### Server and GriefPrevention, dicefurniture, furniturelib, protection lib version:
![image](https://user-images.githubusercontent.com/61608872/103144090-74fa7100-475e-11eb-9ee3-476934ae2475.png)
![image](https://user-images.githubusercontent.com/61608872/103144091-79bf2500-475e-11eb-9a9a-d526bbce80d4.png)
![image](https://user-images.githubusercontent.com/61608872/103144092-7fb50600-475e-11eb-86ed-3be974c1c790.png)
![image](https://user-images.githubusercontent.com/61608872/103144093-86437d80-475e-11eb-9c10-be3b0cae73d1.png)
![image](https://user-images.githubusercontent.com/61608872/103144094-8c395e80-475e-11eb-9bae-7bc1c597286f.png)

**Comment by Ste3et** [comment]
Thats not a bug if you delete your claim the Furniture should disapear -> https://github.com/Ste3et/ProtectionLib/blob/master/src/de/Ste3et_C0st/ProtectionLib/main/plugins/fGriefPrevention.java#L29

**Comment by hkkongou** [comment]
is there any way to disable this function?
Player think this is abnormal and complaint it

**Comment by Ste3et** [comment]
I want to add a way to disable the automatic clearing of the Furnitures

**Comment by Ste3et** [comment]
please try these devBuild version of ProtectionLib -> https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.9.x%20-%201.16.x&buildNummer=234683444
You can find the configurations at /plugins/ProtectionLib/config.yml
You can use a simple /protectionlib reload to change the settings while your server is running
Please give feedback about it.

**Comment by hkkongou** [comment]
thank you very much, i will try it as soon as possible

**Comment by hkkongou** [comment]
it worked, thank you
