### ISSUE TITLE
FurnitureLib can't be enabled please install the correct Protovolib version

### ISSUE THREAD

**Issue by denommenm** [Ste3et/FurnitureLib#69]
![image](https://user-images.githubusercontent.com/14928822/122989638-a7c99e80-d368-11eb-8a46-e23eec3e0c31.png)
We have version: https://ci.dmulloy2.net/job/ProtocolLib/512/
You say to use 511 or greater. Other mods we are using currently all work in 512.

**Comment by Ste3et** [comment]
Please Double check if you use the right version it seems to work for me with build 512 make sure you didn't have two ProtocolLib's in your plugins folder
