### ISSUE TITLE
[bug] Cannot place furniture in Griefdefender claim & anywhere

### ISSUE THREAD

**Issue by hkkongou** [Ste3et/FurnitureLib#70]
after upgraded to latest version of griefdefender, GD2.0, furnitures cannot place inside claim

Error log of furniture lib :
https://paste.gg/p/anonymous/e8e853f18abc4dc88a928a1bd959eab9

[15:23:18 INFO]: FurnitureLib version 2.5.1-dev-8ea829dd
[15:23:27 INFO]: ProtectionLib version 1.2-dev-42967c3c
[15:23:33 INFO]: DiceFurniture version 3.5.0
[15:23:41 INFO]: GriefDefender version 2.0.0-DEV

[15:23:49 INFO]: This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Ste3et** [comment]
Where i can find GriefDefender version 2.0.0-DEV?

**Comment by Ste3et** [comment]
Without an official Repo i can't give support!

**Comment by hkkongou** [comment]
> Where i can find GriefDefender version 2.0.0-DEV?
GD dev replied me privately and he say "GD2.0 DEV is not release. There will be still API changes, any hook will have to wait"
i believe GD2.0 will release soon , within 1-2 weeks , if so i will notify here again

thank you 🙏

**Comment by bloodmc** [comment]
https://github.com/bloodmc/GriefDefenderAPI has been updated for GD 2.0 release.

**Comment by ahdg6** [comment]
This issue should be fixed in the latest version of GDHooks. It's time to close it.
