### ISSUE TITLE
invisible models

### ISSUE THREAD

**Issue by qaikuntur** [Ste3et/FurnitureLib#77]
###URL to /furniture dump side 
https://dicecraft.de/furniture/dump.php?id=3pxx4rsUoijRyma9U3DHp4LE5uNzTgk5

###Please descripe your problem exactly as you can 
I can't see the models in the game
### Is there an error in the console? Use pastebin.com. or hastebin.com Is there a kick message?

**Comment by Ste3et** [comment]
Update your Protocollib https://www.spigotmc.org/resources/protocollib.1997/
