### ISSUE TITLE
Player quit event cause lag spikes

### ISSUE THREAD

**Issue by hkkongou** [Ste3et/FurnitureLib#80]
Paper 1.18.1 215
noticed a lag spike may come from furniturelib when player quit server.
the spark profiler  record is in the following link:
plz help, thank you

https://spark.lucko.me/Ju515fQolO
![image](https://user-images.githubusercontent.com/61608872/159123536-77560757-4cc6-4b61-a597-9b7496248592.png)

**Comment by Ste3et** [comment]
Sorry i can't work with that kind of informations, you need life with that

**Comment by Ste3et** [comment]
please give feedback about these devbuild https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.9.x%20-%201.18.x&buildNummer=496325774
