### ISSUE TITLE
Suggestion to post releases on GitHub too

### ISSUE THREAD

**Issue by TwinkleToes777** [Ste3et/FurnitureLib#81]
It would be nice if as alternative you posted FurnitureLib releases at https://github.com/Ste3et/FurnitureLib/releases
Because SpigotMC uses a very strict configuration of cloudflare that keeps blocking some users and makes it hard to download plugins. There would also be an additional benefit because GitHub releases page supports atom feed readers, which allows to receive notifications for plugin updates without needing of any account.

**Comment by Ste3et** [comment]
https://github.com/Ste3et/FurnitureLib/releases/tag/v2.8.2
