### ISSUE TITLE
updater initialized before setting up config

### ISSUE THREAD

**Issue by doppelganger237** [Ste3et/FurnitureLib#94]
Accidenly find this because this updater is causing my server stucking when starting. I marked these [codes](https://github.com/Ste3et/FurnitureLib/blob/master/FurnitureLib-Core/src/main/java/de/Ste3et_C0st/FurnitureLib/main/FurnitureLib.java#L324C2-L329)
![image](https://github.com/Ste3et/FurnitureLib/assets/30953850/0a9ee5a7-21c9-42f1-a8a2-46c84a7370ae)

**Comment by Ste3et** [comment]
can you try if these push 3e9b84a5c485b54725273d246bab2d0fe965c51f fix your problem?

https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.12.x%20-%201.20.x&buildNummer=918113361

**Comment by doppelganger237** [comment]
Thank you, I tested it and now the promblem is gone. It seems that spiget is using cloudflare, and some addresses of which have been blocked in China, therefore causing timeout when checking for update.
