### ISSUE TITLE
ProtectionLib don't work in plotsquare v7

### ISSUE THREAD

**Issue by sensen1234** [Ste3et/FurnitureLib#96]
![image](https://github.com/Ste3et/FurnitureLib/assets/63025571/e5fb1b83-4743-40ef-a62b-a487ff2ad8b9)
![image](https://github.com/Ste3et/FurnitureLib/assets/63025571/0b7d18a9-c597-42ea-b1b7-5a96f47ec5bc)

**Comment by Ste3et** [comment]
Sorry for the problems i will take a look into it tomorrow.

**Comment by Ste3et** [comment]
Can you try these dev build and give me feedback about the functionality?
https://dicecraft.de/furniture/download.php?plugin=ProtectionLib&build=DevBuild&version=Spigot%201.12.x%20-%201.20.x&buildNummer=1103104552
