### ISSUE TITLE
Can support for SuperiorSkyblock2 be added?

### ISSUE THREAD

**Issue by Angelhellwolf** [Ste3et/FurnitureLib#97]

**Comment by Ste3et** [comment]
SuperiorSkyblock2 support is already added by the ProtectionLib.

https://github.com/Ste3et/ProtectionLib/blob/423494b2385c9813083eaced1316a46e764bb33f/Core/src/main/java/de/Ste3et_C0st/ProtectionLib/main/ProtectionLib.java#L115

Please check `/protectionlib plugins` you can find protectionlib here -> https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/

**Comment by 8MiYile** [comment]
@Ste3et 
![image](https://github.com/user-attachments/assets/06f3000d-e336-4312-acd0-cf6baeb383f9)
are you sure?
